TRAIN:
  ENABLE: True
  DATASET: mydata
  BATCH_SIZE: 16
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
DATA:
  NUM_FRAMES: 10
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /workspace/slowfast/data/MyData
  DECODING_BACKEND: pyav
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
CONTRASTIVE:
  NUM_CLASSES_DOWNSTREAM: 14
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 5
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 13
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5


TEST:
  ENABLE: True
  DATASET: mydata
  BATCH_SIZE: 16
  CHECKPOINT_FILE_PATH: /workspace/slowfast/checkpoints/checkpoint_epoch_00004.pyth
DEMO:
  ENABLE: False
  LABEL_FILE_PATH: /workspace/slowfast/data/MyData/classids.json
  INPUT_VIDEO: /workspace/slowfast/data/MyData/Abuse/Abuse001_x264.mp4
  OUTPUT_FILE: /workspace/slowfast/data/MyData/output.mp4
  COMMON_CLASS_THRES: 0.25
DETECTION:
  ENABLE: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
