TRAIN:
  ENABLE: True
  DATASET: mydata
  BATCH_SIZE: 32
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: False
  CHECKPOINT_FILE_PATH: "/workspace/slowfast/pretrained/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [128, 128]
  TRAIN_CROP_SIZE: 128
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: /workspace/slowfast/data/MyData
  DECODING_BACKEND: pyav

AUG:
  NUM_SAMPLE: 4
  ENABLE: True
  COLOR_JITTER: 0.5
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.4
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
  
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
  
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  
SOLVER:
  BASE_LR: 0.03
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  LR_POLICY: cosine
  MAX_EPOCH: 100
  MOMENTUM: 0.93
  WEIGHT_DECAY: 1e-5
  WARMUP_EPOCHS: 10.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
  
TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /workspace/slowfast/data/MyData/classids.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /workspace/slowfast/data/MyData/class_names.txt
  HISTOGRAM:
    ENABLE: True
MODEL:
  NUM_CLASSES: 13
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.6
TEST:
  ENABLE: True
  DATASET: mydata
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
DEMO:
  ENABLE: False
  LABEL_FILE_PATH: /workspace/slowfast/data/MyData/classids.json
  INPUT_VIDEO: /workspace/slowfast/data/MyData/Abuse/Abuse001_x264.mp4
  OUTPUT_FILE: /workspace/slowfast/data/MyData/output.mp4
  COMMON_CLASS_THRES: 0.25
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
